xendit/xendit-php

README.md
src/XenditPHPClient.php
src/examples/validate_bank_account_holder_name.php

* There is no php client for name validator API now.
* Add php client for name validator

add name validator client

---

README.md
src/XenditPHPClient.php
src/examples/issue_credit_card_refund_example.php
src/examples/issue_credit_card_refund_with_idempotency_example.php

Problem:
We modify credit card refunds endpoint
Solution:
Update client

update refunds method client

---

README.md

Changelog:
Fixing order of param in example for capture credit card

update capture credit card readme

---

README.md
src/XenditPHPClient.php
src/examples/capture_credit_card_payment_with_options_example.php

Changelogs:
Add optional fields for credit card capture

add optional field for capture

---

README.md
examples/PayoutsExample.php
src/Payouts.php
tests/Xendit/PayoutsTest.php

Implemented Payouts Xendit API for PHP Client, added unit tests, code usage examples, and updated readme

Payouts PHP Client

---

examples/RecurringExample.php
src/Recurring.php
tests/Xendit/RecurringTest.php

Implemented Recurring Xendit API for PHP Client, code usage examples, and unit tests. Documentation will be done if the previous PRs are merged

Recurring PHP Client

---

composer.json
examples/CardlessCreditExample.php
src/CardlessCredit.php
tests/Xendit/CardlessCreditTest.php

Implemented cardless credit Xendit API for PHP client, added unit tests, and code usage example. Will do documentation after PRs are merged.

Cardless Credit

---

examples/BalanceExample.php
src/Balance.php
tests/Xendit/BalanceTest.php

Implemented Balance Xendit API for PHP Client, added unit tests and code usage examples. Will do documentation if all PRs are merged.

Balance PHP Client

---

src/Cards.php
src/Disbursements.php
src/Invoice.php

I missed out a few status responses before, so hopefully this PR caught on the rest of status responses.

Added expected status responses

---

CHANGELOG.md
MIGRATE.md
README.md
src/Xendit.php

Added a changelog on what's new, changed, or removed in new version (v2.0.0), add docs on how to update, fixed a typo in a path

Added changelog, update docs, fix typo

---

CHANGELOG.md
MIGRATE.md
README.md
composer.json
examples/BalanceExample.php
examples/CardlessCreditExample.php
examples/CardsExample.php
examples/CardsReverseExample.php
examples/DisbursementsExample.php
examples/EWalletsExample.php
examples/InvoiceExample.php
examples/PayoutsExample.php
examples/RecurringExample.php
examples/RetailExample.php
examples/VirtualAccountExample.php
src/ApiOperations/Create.php
src/ApiOperations/Request.php
src/ApiOperations/Retrieve.php
src/ApiOperations/RetrieveAll.php
src/ApiOperations/Update.php
src/ApiRequestor.php
src/Balance.php
src/Cards.php
src/Disbursements.php
src/EWallets.php
src/Invoice.php
src/Payouts.php
src/Recurring.php
src/Xendit.php
tests/TestCase.php

- Remove `loadApiKey` to give users freedom to choose how they store the secret API key
- Put `headers` in `params` instead
To do:
- Fix and update `README.md`

Changes from previous reviews

---

composer.json
src/Xendit.php

fix(getHttpCli): Fix return type to be nullable

---

.github/workflows/php.yml
README.md
composer.json
composer.lock
examples/QRCodeExample.php
src/ApiOperations/Request.php
src/ApiRequestor.php
src/QRCode.php
src/Xendit.php
tests/Xendit/QRCodeTest.php

- Implementation
- Unit test
- Example Code
- Update Readme guide on how to install packages

QR Code Implentation

---

src/QRCode.php

fix(qr code): Static method for get function

---

README.md
examples/CardlessCreditExample.php
src/CardlessCredit.php
tests/Xendit/CardlessCreditTest.php

Added calculate payment type implementation, example, and unit test

feat(cardless credit): calculate payment type

---

composer.json
composer.lock
examples/PayoutsExample.php
src/Payouts.php
tests/Xendit/PayoutsTest.php

fixes #73
Updated dependencies to fix failing checks, also updated phpunit to `^v8.5.13` to support PHP 8
reference: https://github.com/composer/composer/issues/9529

added required param for create payout

---

README.md
examples/QRCodeExample.php
src/ApiOperations/Request.php
tests/Xendit/EWalletsTest.php

added support for x-api-version header

---

README.md
examples/EWalletsExample.php
src/ApiOperations/Request.php
src/ApiRequestor.php
src/CardlessCredit.php
src/EWallets.php
src/QRCode.php
tests/Xendit/EWalletsTest.php

- `POST` Create eWallet charge
https://developers.xendit.co/api-reference/#create-ewallet-charge
- `GET` Get eWallet charge status
https://developers.xendit.co/api-reference/#get-ewallet-charge-status

New eWallets API

---

composer.json
composer.lock
src/ApiOperations/Retrieve.php

fix(api-operation): change ID type to string

---

README.md
examples/PromotionExample.php
src/Promotion.php
tests/Xendit/PromotionTest.php

added create endpoint for promotion

---

README.md
examples/CustomersExample.php
src/Customers.php
src/Promotion.php
tests/Xendit/CustomersTest.php

- `POST` Create customer
https://developers.xendit.co/api-reference/#create-customer
- `GET` Get customer by reference ID
https://developers.xendit.co/api-reference/#get-customer-by-reference-id
The `Promotion.php` file is carried over because it's reformatted by `pre-commit`

Customers API

---

examples/CustomersExample.php
src/ApiOperations/Request.php
src/Customers.php
tests/Xendit/CustomersTest.php

2020-10-31 version: https://developers.xendit.co/api-reference/customers/customer-object/?bash#2020-10-31
- `POST` Create customer
https://developers.xendit.co/api-reference/#create-customer
- `GET` Get customer by reference ID
https://developers.xendit.co/api-reference/#get-customer-by-reference-id

Customers API (2020-10-31 version)

---

README.md
examples/CustomersExample.php
examples/DirectDebitExample.php
src/ApiOperations/Request.php
src/Customers.php
src/DirectDebit.php
tests/Xendit/CustomersTest.php
tests/Xendit/DirectDebitTest.php

**Linked Account**
- POST Initialize Linked Account Tokenization
- POST Validate OTP for Linked Account Token
- GET Accessible Accounts by Linked Account Token
- DELETE Unbind Linked Account Token
**Payment Method**
- POST Create Payment Method
- GET Payment Methods by Customer ID
**Recurring Payment**
- POST Create Recurring Payment
**Direct Debit**
- POST Create Direct Debit Payment
- POST Validate OTP for Direct Debit Payment
- GET Direct Debit Payment Status by ID
- GET Direct Debit Payment Status by Reference ID
I don't implement the recurring payment part, because it's already been implemented by someone else before.

Direct Debit API

---

README.md
examples/PlatformExample.php
src/Platform.php
tests/Xendit/PlatformTest.php

Hi Team,
- We Love Xendit!
- We Have a big future with Xendit
And now, we need to implement xenPlatform to our project, coz of that we try to contribute to this sdk.
Hopefully you can review ASAP 😃 
Thanks Team!

add xenPlatform

---

composer.lock

udpate composer lock files due to check failing

Update composer lock

---

README.md
examples/PaymentChannelsExample.php
src/PaymentChannels.php
tests/Xendit/PaymentChannelsTest.php

Unbelievable, i cannot see the payment channels in this sdk 😄

add payment channels

---

README.md
composer.json
composer.lock
examples/DisbursementsExample.php
examples/InvoiceExample.php
examples/RecurringExample.php
src/ApiOperations/Retrieve.php
src/ApiOperations/RetrieveAll.php
src/Disbursements.php

- Add params to retrieve and retrieveall
- Update example
- Update readme

Add params to retrieve and retrieveall

---

composer.json
composer.lock
src/QRCode.php
tests/Xendit/QRCodeTest.php
tests/Xendit/TransactionTest.php

The existing version will be denoted as `2020-07-01` while the new one will be `2022-07-31`

feat: support QR Code with API Version 2022-07-31

---

README.md
composer.json
composer.lock
examples/PayoutsNewExample.php
phpunit.xml
phpunit.xml.bak
src/PayoutsNew.php
tests/Xendit/PayoutsNewTest.php

#201 Update Payments New Disbursement Support
- Add [https://developers.xendit.co/api-reference/?php#payouts](https://developers.xendit.co/api-reference/?php#payouts) to SDK with`PaymentsNew` callable class
- Replace documentation from *Payments* into *Payment Links* for better readability
- Update phpunit configuration
Hopefully this PR is merged immediately @ellennugroho

Add Payments New for better disbursement support
